app/views.py
import jwt
import requests
from flask import Blueprint, flash, redirect, render_template, request, url_for
from flask_login import current_user, login_required, login_user, logout_user
from werkzeug.security import check_password_hash

from . import db, login_manager
from .forms import LoginForm, RegisterForm
from .models import User
from .utils import add_new_asset

index_blueprint = Blueprint("index", __name__)
session_blueprint = Blueprint("session", __name__)
functionality_blueprint = Blueprint("functionality", __name__)
menu_blueprint = Blueprint("menu", __name__)


@login_manager.user_loader
def load_user(user_id):
    return User.query.get(int(user_id))


@index_blueprint.route("/")
def index():
    return render_template("index.html")


@login_manager.unauthorized_handler
def unauthorized_callback():
    return redirect(url_for("session.login"))


@session_blueprint.route("/login", methods=["GET", "POST"])
def login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(username=form.username.data).first()
        if user:
            if check_password_hash(user.password, form.password.data):
                login_user(user, remember=form.remember.data)
                flash("You have been successfully logged in.", category="success")
                return redirect(url_for("functionality.dashboard"))

        flash("Invalid username or password.", category="warning")

    return render_template("login.html", form=form)


@session_blueprint.route("/signup", methods=["GET", "POST"])
def signup():
    form = RegisterForm()

    if form.validate_on_submit():
        new_user = User(
            username=form.username.data,
            email=form.email.data,
            password=form.password.data,
        )
        db.session.add(new_user)
        db.session.commit()
        flash("Your account has been successfully created.", category="success")
        return redirect(url_for("session.login"))

    return render_template("signup.html", form=form)


@session_blueprint.route("/logout")
@login_required
def logout():
    logout_user()
    flash("You have been successfully logged out.", category="success")
    return redirect(url_for("index.index"))


@functionality_blueprint.route("/dashboard")
@login_required
def dashboard():
    # jwt_token = jwt.encode({}, "haslo123", algorithm="HS256")
    try:
        resp = requests.get(
            "http://api:5001/all_assets",
            # headers={"X-Access-Token": jwt_token},
            timeout=5,
        )
    except requests.exceptions.ConnectionError:
        return render_template(
            "dashboard.html", name=current_user.username, assets=[], is_error=True
        )

    if resp.status_code != 200:
        return render_template(
            "dashboard.html", name=current_user.username, assets=[], is_error=True
        )

    payload = resp.json()
    assets = []  # got pattern: [{'name': 'Apple', 'abbr': 'A'}, {'}]
    for asset in payload:
        abbr = asset["abbreviation"]
        name = asset["name"]
        assets.append({"abbr": abbr, "name": name})

    return render_template(
        "dashboard.html", name=current_user.username, assets=assets, is_error=False
    )


@menu_blueprint.route("/portfolio")
@login_required
def portfolio():
    # jwt_token = jwt.encode({}, "haslo123", algorithm="HS256")
    try:
        resp = requests.get(
            f"http://api:5001/assets/{current_user.username}",
            # headers={"X-Access-Token": jwt_token},
            timeout=5,
        )
    except requests.exceptions.ConnectionError:
        assets = ["Currently not available"]
    else:
        if resp.status_code != 200:
            assets = ["Currently not available"]
        else:
            assets = resp.json()["available_assets"]

    return render_template("portfolio.html", assets=assets)


@menu_blueprint.route("/new_asset", methods=["GET", "POST"])
@login_required
def new_asset():
    if request.method == "GET":
        try:
            resp = requests.get(
                "http://api:5001/all_assets",
                # headers={"X-Access-Token": jwt_token},
                timeout=5,
            )
        except requests.exceptions.ConnectionError:
            return render_template("new_asset.html", assets=[], is_error=True)

        if resp.status_code != 200:
            return render_template("new_asset.html", assets=[], is_error=True)

        assets = prepare_assets(resp)
        return render_template("new_asset.html", assets=assets, is_error=False)
    elif request.method == "POST":
        return add_new_asset()

@menu_blueprint.route("/account")
@login_required
def account():
    return render_template("account.html", name=current_user.username)

app/templates/account.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %} Title {% endblock %}</title>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% block styles %}
    {% endblock %}

    {% block script %}
    {% endblock %}



</head>
<body>

    {% with messages = get_flashed_messages(with_categories=true) %}
        {% for category, message in messages %}
            <div class="alert alert-{{ category }} alert-dismissible fade show" role="alert">
                <span>{{ message }}</span>
                <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
        {% endfor %}
    {% endwith %}

    <script>

    $(document).ready(function(){
          $(".alert").delay(5000).slideUp(300);
    });

    </script>

    {% block content %}
    {% endblock %}

</body>
</html>

app/templates/dashboard.html
{% extends 'base.html' %}

{% block title %}
Dashboard
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{{url_for('static', filename='dashboard.css')}}">
{% endblock %}


{% block content %}

<div class="container">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <div class="center">
        <div class="left">
            <div class="logo">
                <svg viewBox="0 0 200 400" width="100" height="100">
                    <path d=" M 174.627 77.683 C 173.776 78.815 142.411 133.739 129.968 166.414 C 129.34 168.064 128.78 169.45 128.204 171.119 C 127.727 172.503 127.488 173.714 126.933 175.086 C 126.212 176.871 126.006 177.829 125.667 179.358 C 125.301 181.008 124.477 184.693 124.121 187.63 C 123.856 189.808 123.741 191.662 123.663 193.853 C 123.462 199.472 123.876 204.233 124.636 209.8 C 127.42 230.202 135.691 246.266 147.665 262.895 C 148.73 264.375 149.618 265.639 150.777 267.047 C 152.739 269.432 154.445 271.444 156.857 273.381 C 159.729 275.688 162.496 277.205 165.903 278.596 C 168.996 279.859 171.753 280.586 175.056 281.078 C 178.597 281.605 181.659 281.725 185.216 281.306 C 188.955 280.865 192.024 279.892 195.522 278.517 C 197.728 277.65 199.557 276.802 201.61 275.62 C 204.662 273.863 225.417 262.219 236.258 252.224 C 239.451 249.28 244.212 243.928 244.962 243.452 C 245.712 242.977 264.83 213.834 259.473 198.687 Q 256.513 190.317 211.583 109.026 Q 196.037 82.262 193.522 78.637 C 191.452 75.653 188.937 70.289 183.683 70.278 C 178.429 70.267 175.231 76.89 175.106 76.877 M 236.638 249.594"
                          fill-rule="evenodd" fill="rgb(219,223,255)"></path>
                    <linearGradient id="_lgradient_0" x1="93.56120204019503%" y1="13.017241572786997%"
                                    x2="89.84577303569424%" y2="99.2065293458878%">
                        <stop offset="21%" stop-opacity="1" style="stop-color:rgb(185,193,255)"></stop>
                        <stop offset="100%" stop-opacity="1" style="stop-color:rgb(133,158,255)"></stop>
                        <stop offset="100%" stop-opacity="1" style="stop-color:rgb(185,193,255)"></stop>
                    </linearGradient>
                    <path d=" M 257.964 96.772 C 256.66 97.325 201.992 129.135 174.849 151.174 C 173.478 152.287 172.299 153.205 170.965 154.361 C 169.858 155.319 169.044 156.248 167.877 157.157 C 166.358 158.34 165.7 159.066 164.64 160.219 C 163.496 161.464 160.937 164.24 159.156 166.603 C 157.836 168.354 156.807 169.901 155.641 171.758 C 152.652 176.52 150.624 180.847 148.491 186.045 C 140.676 205.095 139.782 223.141 141.81 243.533 C 141.99 245.347 142.125 246.886 142.422 248.685 C 142.924 251.732 143.393 254.328 144.509 257.213 C 145.838 260.649 147.472 263.349 149.723 266.26 C 151.767 268.902 153.788 270.914 156.4 272.995 C 159.2 275.226 161.798 276.845 165.078 278.284 C 170.601 280.707 175.792 281.319 181.797 281.467 C 194.524 281.78 204.4 276.078 215.486 270.231 C 227.384 263.956 237.187 257.466 245.557 246.856 C 251.368 239.49 255.506 232.649 258.295 223.53 Q 265.443 200.163 271.169 142.865 Q 274.197 111.464 273.837 107.067 C 273.54 103.447 274.053 97.545 269.512 94.902 C 264.971 92.26 258.884 96.388 258.782 96.315 M 211.637 266.477"
                          fill-rule="evenodd" fill="url(#_lgradient_0)"></path>
                </svg>
            </div>
            <div class="company">
                <div class="company-name">TradingApp</div>
                <div class="company-description">All your assets in one place</div>
            </div>
            <div class="navigation">
                <ul style="padding-left:22px">
                    <a href="{{url_for('menu.portfolio')}}">
                        <li><i class="material-icons">loyalty</i><span>Portfolio</span></i></li></a>
                    <a href="{{url_for('menu.account')}}">
                        <li><i class="material-icons">account_box</i><span>Account</span></i></li></a>
                     <a href="{{url_for('index.index')}}">
                        <li><i class="material-icons">logout</i><span>Log out</span></i></li></a>
                    <li></li>
                </ul>
            </div>
        </div>
        <div class="right">
            <div class="title">Dashboard</div>
            <div class="description">Hello, {{ current_user.username }}!</div>
            <div class="row">
                <div class="graph">
                    <svg viewBox="0 0 250 60" width="250" height="90">
                        <path d="M 209.328 17.34 C 221.956 17.588 235.264 32.599 250 22.328" fill="none"
                              vector-effect="non-scaling-stroke" stroke-width="2" stroke="rgb(243,243,250)"
                              stroke-linejoin="miter" stroke-linecap="round" stroke-miterlimit="3"></path>
                        <linearGradient id="_lgradient_1" x1="0%" y1="50%" x2="100%" y2="50%">
                            <stop offset="0%" stop-opacity="1" style="stop-color:rgb(120,113,255)"></stop>
                            <stop offset="100%" stop-opacity="1" style="stop-color:rgb(111,234,255)"></stop>
                        </linearGradient>
                        <path d=" M 0 43.634 C 5.934 43.634 11.318 51.209 17.462 51.342 C 33.219 51.683 30.603 59.567 39.187 59.868 C 46.963 60.141 50.44 44.192 60.537 43.77 C 69.126 43.77 72.129 52.461 79.739 52.433 C 90.904 52.433 94.93 38.455 106.648 39.78 C 129.082 42.317 124.556 27.606 139.157 27.177 C 153.758 26.747 158.235 44.485 171.96 44.725 C 196.438 45.155 189.782 17.1 208.248 17.1"
                              fill="none" vector-effect="non-scaling-stroke" stroke-width="2"
                              stroke="url(#_lgradient_1)" stroke-linejoin="miter" stroke-linecap="round"
                              stroke-miterlimit="3"></path>
                        <path d="M 206.649 17.218 C 206.649 15.739 207.85 14.538 209.328 14.538 C 210.807 14.538 212.008 15.739 212.008 17.218 C 212.008 18.696 210.807 19.897 209.328 19.897 C 207.85 19.897 206.649 18.696 206.649 17.218 Z"
                              fill="rgb(111,232,255)"></path>
                        <text transform="matrix(1,0,0,1,195,5)"
                              style="font-family:&amp;quot;Open Sans&amp;quot;;font-weight:700;font-size:12px;font-style:normal;fill:#6fe8ff;stroke:none;">
                            +14%
                        </text>
                        <div class="stock">
                            <div class="stock-logo paperpillar"><i class="fa fa-inverse fa-angle-double-up"></i></div>
                            <div class="stock-info">
                                <div class="stock-name">AMZN</div>
                                <div class="stock-fullname">Amazon</div>
                            </div>
                        </div>
                    </svg>
                </div>
                <div class="graph">
                    <svg viewBox="0 0 250 60" width="250" height="90">
                        <path d="M 209.328 17.34 C 221.956 17.588 235.264 32.599 250 22.328" fill="none"
                              vector-effect="non-scaling-stroke" stroke-width="2" stroke="rgb(243,243,250)"
                              stroke-linejoin="miter" stroke-linecap="round" stroke-miterlimit="3"></path>
                        <linearGradient id="_lgradient_2" x1="0%" y1="50%" x2="100%" y2="50%">
                            <stop offset="0%" stop-opacity="1" style="stop-color:rgb(248, 135, 129)"></stop>
                            <stop offset="100%" stop-opacity="1" style="stop-color:rgb(247, 198, 130)"></stop>
                        </linearGradient>
                        <path d=" M 0 43.634 C 5.934 43.634 11.318 51.209 17.462 51.342 C 33.219 51.683 30.603 59.567 39.187 59.868 C 46.963 60.141 50.44 44.192 60.537 43.77 C 69.126 43.77 72.129 52.461 79.739 52.433 C 90.904 52.433 94.93 38.455 106.648 39.78 C 129.082 42.317 124.556 27.606 139.157 27.177 C 153.758 26.747 158.235 44.485 171.96 44.725 C 196.438 45.155 189.782 17.1 208.248 17.1"
                              fill="none" vector-effect="non-scaling-stroke" stroke-width="2"
                              stroke="url(#_lgradient_2)" stroke-linejoin="miter" stroke-linecap="round"
                              stroke-miterlimit="3"></path>
                        <path d="M 206.649 17.218 C 206.649 15.739 207.85 14.538 209.328 14.538 C 210.807 14.538 212.008 15.739 212.008 17.218 C 212.008 18.696 210.807 19.897 209.328 19.897 C 207.85 19.897 206.649 18.696 206.649 17.218 Z"
                              fill="rgb(247, 198, 130)"></path>
                        <text transform="matrix(1,0,0,1,195,5)"
                              style="font-family:&amp;quot;Open Sans&amp;quot;;font-weight:700;font-size:12px;font-style:normal;fill:rgb(247, 198, 130);stroke:none;">
                            +14%
                        </text>
                    </svg>
                    <div class="stock">
                        <div class="stock-logo dandruft"><i class="fa fa-inverse fa-circle-thin"></i></div>
                        <div class="stock-info">
                            <div class="stock-name">TSLA</div>
                            <div class="stock-fullname">Tesla</div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="half">
                    <div class="sub-title">All Assets</div>
                    {% if assets|length > 0 %}
                        {% for asset in assets %}
                        <div class="stock">
                            <div class="stock-logo apple"><i class="fa fa-inverse fa-apple"></i></div>
                            <div class="stock-info">
                                <div class="stock-name">{{ asset['abbr'] }}</div>
                                <div class="stock-fullname">{{ asset['name'] }}</div>
                            </div>
                        </div>
                        {% endfor %}
                    {% elif is_error == false %}
                        <div class ="stock">
                            <div class="stock-info">User has no assets!</div>
                        </div>
                    {% else %}
                        <div class ="stock">
                            <div class="stock-info">Currently not available</div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </div>

{% endblock %}

app/templates/index.html
{% extends 'base.html' %}
{% from "macros.html" import render_field %}

{% block title %}
Home Page
{% endblock %}

{% block styles %}
<link rel="stylesheet" href="{{url_for('static', filename='starter-template.css')}}">

{% endblock %}

{% block script %}


{% endblock %}

{% block content %}

  <script>
  function redirectToPage(endpoint){
    console.log('asd');
    window.location.href = `/${endpoint}`;
  }
  </script>


  <div id="index-form-wrap">
    <div class="logo">
      <img src= "{{ url_for('static', filename='trading_app_logo.jpg') }}" width="100" height="90" />
    </div>

    <h2>TradingApp</h2>
    <h3>All your assets in one place</h3>


    <div id="index-form">
      <button onclick="redirectToPage('login')" class="btn-primary btn-block" type="button">Login</button>
      <button onclick="redirectToPage('signup')" class="btn-primary btn-block" type="button">Sign Up</button>

    </div>

  </div>

{% endblock %}

app/templates/new_asset.html
{% extends 'base.html' %}

{% block title %}
My portfolio
{% endblock %}


{% block styles %}
<link rel="stylesheet" href="{{url_for('static', filename='new_asset.css')}}">
{% endblock %}

{% block content %}

<div class="container">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <div class="center">
        <div class="left">
            <div class="logo">
                <svg viewBox="0 0 200 400" width="100" height="100">
                    <path d=" M 174.627 77.683 C 173.776 78.815 142.411 133.739 129.968 166.414 C 129.34 168.064 128.78 169.45 128.204 171.119 C 127.727 172.503 127.488 173.714 126.933 175.086 C 126.212 176.871 126.006 177.829 125.667 179.358 C 125.301 181.008 124.477 184.693 124.121 187.63 C 123.856 189.808 123.741 191.662 123.663 193.853 C 123.462 199.472 123.876 204.233 124.636 209.8 C 127.42 230.202 135.691 246.266 147.665 262.895 C 148.73 264.375 149.618 265.639 150.777 267.047 C 152.739 269.432 154.445 271.444 156.857 273.381 C 159.729 275.688 162.496 277.205 165.903 278.596 C 168.996 279.859 171.753 280.586 175.056 281.078 C 178.597 281.605 181.659 281.725 185.216 281.306 C 188.955 280.865 192.024 279.892 195.522 278.517 C 197.728 277.65 199.557 276.802 201.61 275.62 C 204.662 273.863 225.417 262.219 236.258 252.224 C 239.451 249.28 244.212 243.928 244.962 243.452 C 245.712 242.977 264.83 213.834 259.473 198.687 Q 256.513 190.317 211.583 109.026 Q 196.037 82.262 193.522 78.637 C 191.452 75.653 188.937 70.289 183.683 70.278 C 178.429 70.267 175.231 76.89 175.106 76.877 M 236.638 249.594"
                          fill-rule="evenodd" fill="rgb(219,223,255)"></path>
                    <linearGradient id="_lgradient_0" x1="93.56120204019503%" y1="13.017241572786997%"
                                    x2="89.84577303569424%" y2="99.2065293458878%">
                        <stop offset="21%" stop-opacity="1" style="stop-color:rgb(185,193,255)"></stop>
                        <stop offset="100%" stop-opacity="1" style="stop-color:rgb(133,158,255)"></stop>
                        <stop offset="100%" stop-opacity="1" style="stop-color:rgb(185,193,255)"></stop>
                    </linearGradient>
                    <path d=" M 257.964 96.772 C 256.66 97.325 201.992 129.135 174.849 151.174 C 173.478 152.287 172.299 153.205 170.965 154.361 C 169.858 155.319 169.044 156.248 167.877 157.157 C 166.358 158.34 165.7 159.066 164.64 160.219 C 163.496 161.464 160.937 164.24 159.156 166.603 C 157.836 168.354 156.807 169.901 155.641 171.758 C 152.652 176.52 150.624 180.847 148.491 186.045 C 140.676 205.095 139.782 223.141 141.81 243.533 C 141.99 245.347 142.125 246.886 142.422 248.685 C 142.924 251.732 143.393 254.328 144.509 257.213 C 145.838 260.649 147.472 263.349 149.723 266.26 C 151.767 268.902 153.788 270.914 156.4 272.995 C 159.2 275.226 161.798 276.845 165.078 278.284 C 170.601 280.707 175.792 281.319 181.797 281.467 C 194.524 281.78 204.4 276.078 215.486 270.231 C 227.384 263.956 237.187 257.466 245.557 246.856 C 251.368 239.49 255.506 232.649 258.295 223.53 Q 265.443 200.163 271.169 142.865 Q 274.197 111.464 273.837 107.067 C 273.54 103.447 274.053 97.545 269.512 94.902 C 264.971 92.26 258.884 96.388 258.782 96.315 M 211.637 266.477"
                          fill-rule="evenodd" fill="url(#_lgradient_0)"></path>
                </svg>
            </div>
            <div class="company">
                <div class="company-name">TradingApp</div>
                <div class="company-description">All your assets in one place</div>
            </div>
            <div class="navigation">
                <ul style="padding-left:22px">
                    <a href="{{url_for('functionality.dashboard')}}">
                        <li><i class="material-icons">dashboard</i><span>Dashboard</span></i></li>
                    </a>
                    <a href="{{url_for('menu.account')}}">
                        <li><i class="material-icons">account_box</i><span>Account</span></i></li>
                    </a>
                    <a href="{{url_for('index.index')}}">
                        <li><i class="material-icons">logout</i><span>Log out</span></i></li>
                    </a>
                    <li></li>
                </ul>
            </div>
        </div>
        <div class="right">
            <div class="title">New Assets</div>
            <div class="row">
                <div class="half">
                    <div class="sub-title">New Assets</div>
                    <form action="#" method="POST" > 
                        <select name="asset_choice">
                            {% for dict in assets %}
                            <option value="{{ dict['name'] }}">{{ dict['abbr'] }}</option> 
                            {% endfor %}
                        </select>
                        <input type="submit"/>
                    </form>

                </div>
            </div>
        </div>

        {% endblock %}

app/templates/portfolio.html
{% extends 'base.html' %}

{% block title %}
My portfolio
{% endblock %}

{% block script %}
<script>
    {% if assets|length > 0 %}
        {% for asset in assets %}
              const source = new EventSource("http://api:5001/asset/{{ asset }}/value");
              source.onmessage = function (event) {
                    const div = document.getElementById("asset-price-{{ asset }}");

                    const data = JSON.parse(event.data);
                    current_value = data["current_value"];

                    div.textContent = current_value;
              }
        {% endfor %}
    {% endif %}


</script>
{% endblock %}


{% block styles %}
<link rel="stylesheet" href="{{url_for('static', filename='portfolio.css')}}">
{% endblock %}

{% block content %}

<div class="container">

    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">

    <div class="center">
        <div class="left">
            <div class="logo">
                <svg viewBox="0 0 200 400" width="100" height="100">
                    <path d=" M 174.627 77.683 C 173.776 78.815 142.411 133.739 129.968 166.414 C 129.34 168.064 128.78 169.45 128.204 171.119 C 127.727 172.503 127.488 173.714 126.933 175.086 C 126.212 176.871 126.006 177.829 125.667 179.358 C 125.301 181.008 124.477 184.693 124.121 187.63 C 123.856 189.808 123.741 191.662 123.663 193.853 C 123.462 199.472 123.876 204.233 124.636 209.8 C 127.42 230.202 135.691 246.266 147.665 262.895 C 148.73 264.375 149.618 265.639 150.777 267.047 C 152.739 269.432 154.445 271.444 156.857 273.381 C 159.729 275.688 162.496 277.205 165.903 278.596 C 168.996 279.859 171.753 280.586 175.056 281.078 C 178.597 281.605 181.659 281.725 185.216 281.306 C 188.955 280.865 192.024 279.892 195.522 278.517 C 197.728 277.65 199.557 276.802 201.61 275.62 C 204.662 273.863 225.417 262.219 236.258 252.224 C 239.451 249.28 244.212 243.928 244.962 243.452 C 245.712 242.977 264.83 213.834 259.473 198.687 Q 256.513 190.317 211.583 109.026 Q 196.037 82.262 193.522 78.637 C 191.452 75.653 188.937 70.289 183.683 70.278 C 178.429 70.267 175.231 76.89 175.106 76.877 M 236.638 249.594"
                          fill-rule="evenodd" fill="rgb(219,223,255)"></path>
                    <linearGradient id="_lgradient_0" x1="93.56120204019503%" y1="13.017241572786997%"
                                    x2="89.84577303569424%" y2="99.2065293458878%">
                        <stop offset="21%" stop-opacity="1" style="stop-color:rgb(185,193,255)"></stop>
                        <stop offset="100%" stop-opacity="1" style="stop-color:rgb(133,158,255)"></stop>
                        <stop offset="100%" stop-opacity="1" style="stop-color:rgb(185,193,255)"></stop>
                    </linearGradient>
                    <path d=" M 257.964 96.772 C 256.66 97.325 201.992 129.135 174.849 151.174 C 173.478 152.287 172.299 153.205 170.965 154.361 C 169.858 155.319 169.044 156.248 167.877 157.157 C 166.358 158.34 165.7 159.066 164.64 160.219 C 163.496 161.464 160.937 164.24 159.156 166.603 C 157.836 168.354 156.807 169.901 155.641 171.758 C 152.652 176.52 150.624 180.847 148.491 186.045 C 140.676 205.095 139.782 223.141 141.81 243.533 C 141.99 245.347 142.125 246.886 142.422 248.685 C 142.924 251.732 143.393 254.328 144.509 257.213 C 145.838 260.649 147.472 263.349 149.723 266.26 C 151.767 268.902 153.788 270.914 156.4 272.995 C 159.2 275.226 161.798 276.845 165.078 278.284 C 170.601 280.707 175.792 281.319 181.797 281.467 C 194.524 281.78 204.4 276.078 215.486 270.231 C 227.384 263.956 237.187 257.466 245.557 246.856 C 251.368 239.49 255.506 232.649 258.295 223.53 Q 265.443 200.163 271.169 142.865 Q 274.197 111.464 273.837 107.067 C 273.54 103.447 274.053 97.545 269.512 94.902 C 264.971 92.26 258.884 96.388 258.782 96.315 M 211.637 266.477"
                          fill-rule="evenodd" fill="url(#_lgradient_0)"></path>
                </svg>
            </div>
            <div class="company">
                <div class="company-name">TradingApp</div>
                <div class="company-description">All your assets in one place</div>
            </div>
            <div class="navigation">
                <ul style="padding-left:22px">
                    <a href="{{url_for('functionality.dashboard')}}">
                        <li><i class="material-icons">dashboard</i><span>Dashboard</span></i></li>
                    </a>
                    <a href="{{url_for('menu.account')}}">
                        <li><i class="material-icons">account_box</i><span>Account</span></i></li>
                    </a>
                    <a href="{{url_for('index.index')}}">
                        <li><i class="material-icons">logout</i><span>Log out</span></i></li>
                    </a>
                    <li></li>
                </ul>
            </div>
        </div>
        <div class="right">
            <div class="title">My portfolio</div>
            <div class="description">User, you have {{ assets | length }} assets</div>
            <div class="row">
                <div class="half">
                    <div class="sub-title">My Assets</div>
                    {% if assets|length > 0 %}
                    {% for asset in assets %}
                    <div class="stock">
                        <div class="stock-logo apple"><i class="fa fa-inverse fa-apple"></i></div>
                        <div class="stock-info">
                            <a href="/details/{{ asset }}">
                                <div class="stock-fullname">{{ asset }}</div>
                            </a>
                            <div id="asset-price-{{ asset }}"></div>
                        </div>
                    </div>
                    {% endfor %}
                    {% endif %}
                </div>
            </div>
        </div>

        {% endblock %}